module.exports = {
    am: 'Amharic',
    ar: 'Arabic',
    eu: 'Basque',
    bn: 'Bengali',
    'en-GB': 'English (UK)',
    'pt-BR': 'Portuguese (Brazil)',
    bg: 'Bulgarian',
    ca: 'Catalan',
    chr: 'Cherokee',
    hr: 'Croatian',
    cs: 'Czech',
    da: 'Danish',
    nl: 'Dutch',
    en: 'English (US)',
    et: 'Estonian',
    fil: 'Filipino',
    fi: 'Finnish',
    fr: 'French',
    de: 'German',
    el: 'Greek',
    gu: 'Gujarati',
    iw: 'Hebrew',
    hi: 'Hindi',
    hu: 'Hungarian',
    is: 'Icelandic',
    id: 'Indonesian',
    it: 'Italian',
    ja: 'Japanese',
    kn: 'Kannada',
    ko: 'Korean',
    lv: 'Latvian',
    lt: 'Lithuanian',
    ms: 'Malay',
    ml: 'Malayalam',
    mr: 'Marathi',
    no: 'Norwegian',
    pl: 'Polish',
    'pt-PT': 'Portuguese (Portugal)',
    ro: 'Romanian',
    ru: 'Russian',
    sr: 'Serbian',
    'zh-CN': 'Chinese (PRC)',
    sk: 'Slovak',
    sl: 'Slovenian',
    es: 'Spanish',
    sw: 'Swahili',
    sv: 'Swedish',
    ta: 'Tamil',
    te: 'Telugu',
    th: 'Thai',
    'zh-TW': 'Chinese (Taiwan)',
    tr: 'Turkish',
    ur: 'Urdu',
    uk: 'Ukrainian',
    vi: 'Vietnamese',
    cy: 'Welsh'
  }
// module.exports  = 
//     [
//         ["Amharic","am"  ],
//         ["Arabic","ar"  ],
//         ["Basque","eu"  ],
//         ["Bengali","bn"  ],
//         ["English (UK)","en-GB"  ],
//         ["Portuguese (Brazil)","pt-BR"  ],
//         ["Bulgarian","bg"  ],
//         ["Catalan","ca"  ],
//         ["Cherokee","chr"  ],
//         ["Croatian","hr"  ],
//         ["Czech","cs"  ],
//         ["Danish","da"  ],
//         ["Dutch","nl"  ],
//         ["English (US)","en"  ],
//         ["Estonian","et"  ],
//         ["Filipino","fil"  ],
//         ["Finnish","fi"  ],
//         ["French","fr"  ],
//         ["German","de"  ],
//         ["Greek","el"  ],
//         ["Gujarati","gu"  ],
//         ["Hebrew","iw"  ],
//         ["Hindi","hi"  ],
//         ["Hungarian","hu"  ],
//         ["Icelandic","is"  ],
//         ["Indonesian","id"  ],
//         ["Italian","it"  ],
//         ["Japanese","ja"  ],
//         ["Kannada","kn"  ],
//         ["Korean","ko"  ],
//         ["Latvian","lv"  ],
//         ["Lithuanian","lt"  ],
//         ["Malay","ms"  ],
//         ["Malayalam","ml"  ],
//         ["Marathi","mr"  ],
//         ["Norwegian","no"  ],
//         ["Polish","pl"  ],
//         ["Portuguese (Portugal)","pt-PT"  ],
//         ["Romanian","ro"  ],
//         ["Russian","ru"  ],
//         ["Serbian","sr"  ],
//         ["Chinese (PRC)","zh-CN"  ],
//         ["Slovak","sk"  ],
//         ["Slovenian","sl"  ],
//         ["Spanish","es"  ],
//         ["Swahili","sw"  ],
//         ["Swedish","sv"  ],
//         ["Tamil","ta"  ],
//         ["Telugu","te"  ],
//         ["Thai","th"  ],
//         ["Chinese (Taiwan)","zh-TW"  ],
//         ["Turkish","tr"  ],
//         ["Urdu","ur"  ],
//         ["Ukrainian","uk"  ],
//         ["Vietnamese","vi"  ],
//         ["Welsh","cy"  ]
//       ]

